#!/bin/bash
temp="false"
separator="."
xiegang="/"
#Filter
filter=(Android.mk AndroidManifest.xml .java lint styles.xml colors.xml strings.xml arrays.xml attrs.xml ids.xml bools.xml dimens.xml config.xml donottranslate.xml integers.xml symbols.xml themes.xml)
#var=$(ls -lR |grep -v ^d|awk '{print $9}' |tr -s '\n')
var=`find . -type f`

for i in $var
do
#######
for j in ${filter[@]}
do
if [[ $i == *$j* ]];then
temp=$j
break
else
temp="false"
fi
done

if [[ $temp != "false" ]];then
  echo "$temp File pass !!!"
else
  filename1=${i##*$xiegang}
  #echo "带后缀文件名:  $filename1"
  filename=${filename1%$separator*}
  #echo "不带后缀文件名: $filename"
  var1=$(grep -ri $filename . | wc -l)
  #echo "变量： $var1"
  if [ $var1 -eq 0 ];then
  echo "Delete： $i File"
  rm -f $i
  fi
fi
#######
done
